-- Control-plane schema for the tenancy bounded context.
-- All identifiers are UUIDs generated by the application for portability.

CREATE TABLE tenants (
    id         UUID PRIMARY KEY,
    name       TEXT NOT NULL,
    slug       TEXT NOT NULL UNIQUE,
    plan       TEXT NOT NULL,
    status     TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT tenants_plan_chk   CHECK (plan   IN ('free','team','enterprise')),
    CONSTRAINT tenants_status_chk CHECK (status IN ('active','suspended'))
);

CREATE TABLE users (
    id               UUID PRIMARY KEY,
    email            TEXT NOT NULL UNIQUE,
    display_name     TEXT NOT NULL,
    external_subject TEXT NOT NULL DEFAULT '',
    created_at       TIMESTAMPTZ NOT NULL
);

CREATE TABLE memberships (
    tenant_id  UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id    UUID NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
    role       TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (tenant_id, user_id),
    CONSTRAINT memberships_role_chk CHECK (role IN ('owner','admin','editor','viewer'))
);

CREATE INDEX memberships_user_idx  ON memberships (user_id);
CREATE INDEX memberships_owner_idx ON memberships (tenant_id) WHERE role = 'owner';

CREATE TABLE api_keys (
    id           UUID PRIMARY KEY,
    tenant_id    UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name         TEXT NOT NULL,
    prefix       TEXT NOT NULL UNIQUE,
    hash         TEXT NOT NULL,
    scopes       TEXT[] NOT NULL,
    status       TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL,
    expires_at   TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    CONSTRAINT api_keys_status_chk CHECK (status IN ('active','revoked'))
);

CREATE INDEX api_keys_tenant_idx ON api_keys (tenant_id);
-- prefix is UNIQUE (above), giving an O(1) indexed lookup on the auth hot path.

CREATE TABLE outbox (
    id          UUID PRIMARY KEY,
    event_name  TEXT NOT NULL,
    payload     JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ
);

-- Partial index lets the Phase 2 relay poll only unpublished events cheaply.
CREATE INDEX outbox_unpublished_idx ON outbox (created_at) WHERE published_at IS NULL;
